language: r
cache: packages
pandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

notifications:
  email: false

after_success: |
  if [ -n "$GITHUB_TOKEN" ]; then
    git config user.name "traviscibot"
    git config user.email "brechtdvgmail.com"
    git checkout -q master
    git add docs/
    git commit --allow-empty -m "Automatic build [skip ci]"
    git remote add authenticated https://brechtdv:$GITHUB_TOKEN@github.com/brechtdv/BODA.git
    git push --quiet authenticated master &>/dev/null
  fi
  
