language: r
cache: packages
pandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_build.sh

script:
  - ./_build.sh

notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_PAT
  repo: brechtdv/BODA
  target_branch: master
