# (PART\*)  Part I: Calculating DALYs {-} 

# Introduction

The ultimate goal of public health policy is to protect and promote the population’s health (Devleesschauwer et al., 2014a). This requires information on the health status of the population, often referred to as the “burden of disease”. In order to make relevant decisions and set appropriate priorities, policy makers need to be informed about the size of health problems in the population, the groups that are particularly at risk, and the trends in the state of health over time. In addition, an accurate estimate of the population’s health status can be used for determining the expected health care use and is vital for prioritizing effective interventions and evaluating their impact and cost-effectiveness (Tan-Torres Edejer et al., 2003).

As public health is a multifactorial phenomenon with many facets, the disease burden of the population can be described by a variety of indicators. Typical indicators of population health are life expectancy, cause-specific mortality rates, numbers of new and existing cases of specific diseases (i.e., incidence and prevalence), perceived health, the occurrence of physical and mental limitations and disability, but also more indirect measures, such as absenteeism, incapacity of work, and the use of medical facilities and the associated costs. However, all these indicators highlight only one facet of public health, i.e., either mortality or morbidity.

Summarizing public health in terms of mortality-based indicators, such as life expectancy, dates from the time when only reliable data for mortality existed. In many countries, however, one has been confronted with ageing populations and an epidemiological transition of public health problems. The importance of early mortality due to plagues and famines has been replaced by chronic, non-communicable diseases, while communicable diseases remain a real threat, causing a “double burden” (Marshall, 2004). Cardiovascular diseases and cancers have replaced infectious diseases as the main causes of death. However, these diseases are also associated with an important morbidity component, due to the life prolonging effect of continuously improving medical practice (Jelenc et al., 2012). Moreover, not only an extended life expectancy per se is aimed for, living these extra years in good health has become just as important (Bryant et al., 2001). As a result, current health policy requires a global overview of public health, one that combines morbidity and mortality and takes account of health-related quality of life (Robine et al. 2013).

Given the importance of combining morbidity and mortality, several summary measures of population health (SMPH) have been proposed and implemented (Murray et al., 2000; Table 1). SMPHs may be divided into two broad families: health expectancies or experiences and health gaps, but all have in common that they use “time” as the common measure for quantifying health or health loss. The most powerful SMPHs are those that are able to combine morbidity and mortality into a single figure.

Table: (\#smph) Classification of summary measures of population health

|                       | Health Experience                                                                                                                                          | Health Gap                                                                                             |
|-----------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------|
| Mortality             | Life Expectancy                                                                                                                                            | Potential Years of Life Lost<br>(Years of Potential Life Lost)<br>Standard Expected Years of Life Lost |
| Morbidity             | Quality-Adjusted Life Year                                                                                                                                 | Years Lived with Disability                                                                            |
| Morbidity & Mortality | Active Life Expectancy<br>Disability-Free Life Expectancy<br>Healthy Life Years<br>Quality-Adjusted Life Expectancy<br>Disability-Adjusted Life Expectancy | Disability-Adjusted Life Year                                                                          |

Driven by the influential Global Burden of Disease (GBD) projects initiated in the early 1990s (Murray and Lopez, 1996), the Disability-Adjusted Life Year (DALY) has become the dominant SMPH for quantifying burden of disease. The DALY metric has therefore been selected as key SMPH for the Belgian National Burden of Disease study. DALYs measure the health gap from a life lived in perfect health, and quantify this health gap as the number of healthy life years lost due to morbidity and mortality. Although the basic DALY formulas are rather straightforward, the calculation of DALYs, like any other SMPH, requires several assumptions, some of which are not always obvious. Furthermore, DALY-based burden of disease studies are almost always confronted by uncertainties and almost always require manipulations of epidemiological data.
