--- 
title: "Burden of Disease Assessment: A Practical Guide"
author: "Brecht Devleesschauwer"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: brechtdv/BODA
description: "Getting started with burden of disease assessment"
---

# Preface {-}

Disability-Adjusted Life Years (DALYs) have become a key indicator in descriptive epidemiology. DALYs represent the number of healthy life years lost due to ill health and mortality, and allow comparing the population health impact of diseases, injuries and risk factors.

Although the DALY concept has been introduced nearly 30 years ago, there is still little guidance available on their calculation. This book aims to address this gap, through a combination of theoretical sections, simplified examples, and real-life experiences.

This book is the result of interactions and collaborations within the European Burden of Disease Network (COST Action CA18218), supported by COST (cooperation in science and technology). Further information on the network is available via <https://www.burden-eu.net>.

## Why read this book {-}

This book is primarily intended for students, researchers and public health professionals interested in learning how to calculate DALYs.

However, it should also be noted that the **best way of learning is by doing**. We therefore hope that this book can encourage you to get started with your own calculation examples. 

## Structure of the book {-}

The first part of the book is dedicated to the basic concepts of DALY calculations. Starting from simple examples, different layers of complexity will be introduced.

The second part of the book is dedicated to national burden of disease studies.

# About the authors {-}

## Brecht Devleesschauwer {-}

Some info here.

<https://twitter.com/brechtdv>
